PresentationLayer/Areas/Admin/Controllers/AdminCategoryController.cs
using BusinessLayer.Abstract;
using DTOLayer;
using EntityLayer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PresentationLayer.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCategoryController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly UserManager<AppUser> _userManager;

        public AdminCategoryController(IProductService productService, ICategoryService categoryService, UserManager<AppUser> userManager)
        {
            _productService = productService;
            _categoryService = categoryService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult InsertCategory()
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
               
                return View();

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }

     



        [HttpPost]
        public IActionResult InsertCategory(AddCategoryDto newCategory)
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                _categoryService.TInsert(new Category()
                {
                    CategoryName= newCategory.CategoryName
                });

                return View();

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }


        public IActionResult GetCategoryList()
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                var categories = _categoryService.TGetList();

                return View(categories);

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }



        [HttpGet]
        public IActionResult EditCategory(int categoryId)
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                var category = _categoryService.TGetByID(categoryId);

                return View(category);

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }

        [HttpPost]
        public IActionResult EditCategory(Category category)
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                _categoryService.TUpdate(category);

                return View();

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }






        [HttpPost("AdminCategory/deleteCategory")]
        public IActionResult removeCategory(int categoryId)
        {
            Console.WriteLine("ctid" + categoryId);
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                var category = _categoryService.TGetByID(categoryId);
                _categoryService.TDelete(category);

                return Ok();

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }













    }
}

PresentationLayer/Areas/Admin/Controllers/AdminProductController.cs
using BusinessLayer.Abstract;
using DTOLayer;
using EntityLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PresentationLayer.Areas.Admin.Controllers
{

    [Area("Admin")]
   // [Authorize(Roles = "Admin")]

    public class AdminProductController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IProductCategoryService _productCategoryService;
        private readonly UserManager<AppUser> _userManager;

        public AdminProductController(SignInManager<AppUser> signInManager, IProductService productService, ICategoryService categoryService, IProductCategoryService productCategoryService, UserManager<AppUser> userManager)
        {
            _signInManager = signInManager;
            _productService = productService;
            _categoryService = categoryService;
            _productCategoryService = productCategoryService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
               
                ViewBag.username = user.UserName;
                return View();
            }
            else
            {
                return RedirectToAction("Error", "Home");
            }



        }
      
        [HttpGet]
        public IActionResult InsertProduct()
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                var cats = _categoryService.TGetList();
                ViewBag.v = cats;
                return View();

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }

        [HttpPost]
        public IActionResult InsertProduct(AddProductDto addProductDto)
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }

            if (_userManager.IsInRoleAsync(user, "Admin").Result) { 
                Console.WriteLine("ppppp:" + addProductDto.ProductCategoryIds.Count);
            Product product = new Product() { };

            List<ProductCategory> selectedCategories = new List<ProductCategory>();

            foreach (var c in addProductDto.ProductCategoryIds)
            {
                selectedCategories.Add(new ProductCategory() { CategoryId = c });
            }


            product.ProductTitle = addProductDto.ProductTitle;
            product.ProductPhotoUrl = addProductDto.ProductPhotoUrl;
            product.ProductPrice = addProductDto.ProductPrice;
            product.ProductDescription = addProductDto.ProductDescription;
            product.ProductName = addProductDto.ProductName;


            product.ProductCategory = selectedCategories;



            _productService.TInsert(product);


            return View();
                 }

            else
            {
                return RedirectToAction("Error", "Home");

            }
        
        
            }
  

        [HttpGet]
        public IActionResult EditProduct(int productId)
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                var product = _productService.TGetByID(productId);
                var categories=_categoryService.TGetList();
                ViewBag.v=categories;


              


                return View(product);

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }

        [HttpPost]
        public IActionResult EditProduct(AddProductDto   productDto)
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                var product = new Product()
                {
                   ProductName = productDto.ProductName,
                   ProductDescription= productDto.ProductDescription,
                   ProductPrice= productDto.ProductPrice,
                   ProductPhotoUrl= productDto.ProductPhotoUrl,
                   ProductTitle= productDto.ProductTitle,


                };
                List<ProductCategory> selectedCategories = new List<ProductCategory>();

                foreach (var c in productDto.ProductCategoryIds)
                {
                    Console.WriteLine("category is " +c);
                    selectedCategories.Add(new ProductCategory() { CategoryId = c });
                }
                product.ProductCategory = selectedCategories;
                
             
                product.Id = (int)productDto.ProductId;
                










                _productCategoryService.TDeleteAllProductCategoryWithCategoryId(product.Id);


                _productService.TUpdate(product);

                return View();

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }


        public IActionResult GetProductList()
        {
            var products = _productService.TGetList();
            
            return View(products);
        }

        [HttpPost("AdminProduct/deleteProduct")]
        public IActionResult removeProduct(int productId)
        {
    
            var user = _userManager.GetUserAsync(User).Result;
            if (user == null)
            {
                return RedirectToAction("Error", "Home");

            }
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
            {
                Console.WriteLine("productid:" + productId);
                var product = _productService.TGetByID(productId);
                _productService.TDelete(product);

                return Ok();

            }
            else
            {
                return RedirectToAction("/", "Error");
            }


        }





    }
}

PresentationLayer/Areas/Admin/Views/AdminCategory/EditCategory.cshtml
@using EntityLayer.Models
@model Category
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<form method="post" style="width:70%;margin:auto;">
    <h1>EditCategory</h1>

    <div class="mb-3">
        <label for="productNameInput" class="form-label">Category Name</label>
        <input  asp-for=CategoryName class="form-control" id="productNameInput" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

PresentationLayer/Areas/Admin/Views/AdminCategory/GetCategoryList.cshtml
@using EntityLayer.Models;
@model List<Category>
@{
    ViewData["Title"] = "GetCategoryList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>GetCategoryList</h1>
<table style="width:100%; border-collapse:collapse">
    <tr style={{ textAlign: 'left' }}>
        <th>Id</th>
        
        <th>Title</th>
       
        <th>Operations</th>
    </tr>

    @foreach(var item in Model){

    <tr data-rowid="@item.Id" style={{ textAlign: 'left' , padding: '8px' }}>
        <td>@item.Id</td>

      
        <td>@item.CategoryName</td>

       


        <td>
              <a asp-area="Admin" asp-controller="AdminProduct" asp-action="EditProduct" asp-route-productId="@item.Id" class="btn" style="background-color:orange;">
                 
                Edit
            </a>
                <a type="button" onclick="removeCategory('@item.Id')" class="btn" style="background-color:red;">
                 
                Delete
            </a>

        </td>
    </tr>

    }
 

</table>

<script>
    function removeCategory(categoryId) {

        var confirmed = confirm("Are you sure ? Item will be deleted.");
        if (confirmed) {
            document.querySelector(`tr[data-rowid="${categoryId}"]`).remove()
           

            fetch(`/AdminCategory/deleteCategory?categoryId=${categoryId}`, {method: 'POST',
        
        
        })
        }
    }
</script>

PresentationLayer/Areas/Admin/Views/AdminCategory/InsertCategory.cshtml
@using DTOLayer;
@model AddCategoryDto
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@{
    ViewData["Title"] = "InsertCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post" style="width:70%;margin:auto;">
    <h1>Add Category</h1>
  

    <div class="mb-3">
        <label for="categoryNameInput" class="form-label">Category Name</label>
        <input type="text" asp-for="CategoryName" class="form-control" id="categoryNameInput" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>